name: Docker Build core-app

on:
  push:
    #    paths:
    #      - "romeano/**"
    branches:
      - "master"
  workflow_dispatch:

defaults:
  run:
    working-directory: romeano

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/core-app

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sanity Check ‚úÖ
        run: |
          echo "  - Node version: $(node -v)"
          echo "  - NPM version: $(npm -v)"
          echo "  - Yarn version: $(yarn -v)"
          echo "  - Working in directory: $(pwd)"
          echo "  - IMAGE_ID as shell var: ${IMAGE_ID}"
          echo "  - IMAGE_ID as expression: ${{ env.IMAGE_ID }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./romeano
          push: true
          tags: ${{ env.IMAGE_ID }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          #cache docs: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          #cache beta: https://github.com/docker/build-push-action/pull/406#issuecomment-879184394

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
