name: Build and Deploy Client
on: [ push ]

defaults:
  run:
    working-directory: client

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Sanity Check + Yarn 2 âœ…
        run: |
          echo "  - Node version: $(node -v)"
          echo "  - NPM version: $(npm -v)"
          yarn set version berry
          echo "  - Yarn version: $(yarn -v)"
          echo "  - Working in directory: $(pwd)"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps ğŸ”§
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Build FE ğŸ”§
        run: yarn ghpublish

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: client/out # source folder path
          repository-name: Romeano-Inc/gh-pages-frontend # target repo name
          branch: master # target branch name
          target-folder: docs
          clean: true # cleans the target repo destination
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
