name: Build and Deploy
on: [ push ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install deps and Build FE ğŸ”§
        working-directory: client
        run: |
          echo Node version: $(node -v)
          echo NPM version: $(npm -v)
          yarn set version berry
          echo yarn version: $(yarn -v)
          yarn install
          yarn ghpublish

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: out # source folder path
          repository-name: gh-pages-frontend # target repo name
          branch: master # target branch name
          target-folder: docs
          clean: true # cleans the target repo destination
