name: Build and Deploy
on: [ push ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install deps and Build FE ğŸ”§
        working-directory: client
        run: |
          node -v
          npm -v
          yarn -v
          yarn set version berry
          ls -la
          yarn -v
          yarn
          yarn build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: out # source folder path
          repository-name: gh-pages-frontend # target repo name
          branch: master # target branch name
          clean: true # cleans the target repo destination

